version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
  identical-code:
    enabled: false
exclude_patterns:
- "**/*.test.js"
- "src/serviceWorker.js"
- "src/index.css"
- "node_modules/"
plugins:
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
      fallback-colors:
        enabled: false
      box-model:
          enabled: false
  eslint:
    enabled: true
    config:
      extensions:
        - .js
        - .jsx
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  shellcheck:
    enabled: true
  stylelint:
    enabled: true
